### ISSUE TITLE
Help with 'good first issue'

### ISSUE THREAD

**Issue by pedrorgirardi** [oakmac/tree-sitter-clojure#17]
I see there are a few 'good first issue' issues and I would like to try to help with them. I have very little knowledge on this though, so I would really appreciate if you could give me a short intro to the project.

**Comment by oakmac** [comment]
Great! It will be excellent to have some help with this project :)

I am traveling through most of next week and may have limited availability, but maybe I can help walk you through an initial issue.

Do you have this repo cloned and able to build + run the tests? ie: the steps outlined in [Development Setup](https://github.com/oakmac/tree-sitter-clojure#development)?

**Comment by pedrorgirardi** [comment]
Cool! I cloned the repo, ran the tests and all seems to be working :)

During the week I will go through Tree sitter's documentation to learn how things work and then I will take a look at the tests/corpus and hopefully, things will make some sense.

**Comment by shaunlebron** [comment]
Just a short rundown:

## Testing

[`corpus/`](https://github.com/oakmac/tree-sitter-clojure/tree/master/corpus) has readable tests, each with 1) a title, 2) clojure code to parse, and 3) an expected AST:

```
=====================================
Vector - []
=====================================

[]
[true]
["a" :b 3]

---

(program
  (vector)
  (vector (boolean (true)))
  (vector (string) (keyword) (number (number_long))))
```

## Grammar

Parsing rules are in [grammar.js](https://github.com/oakmac/tree-sitter-clojure/blob/master/grammar.js). Each symbol in the expected AST shown above (e.g. `vector`, `boolean`) are keys in the `rules` object.

Any key starting with an underscore is a sort of transparent grouping that gets flattened in the AST.  For example, if you parse the following clojure code:

```
[true]
```

It first looks like this:

```
(program
  (_anything (_literals (_collection_literals
    (vector
      (_vector (_anything (_literals
        (boolean (true))))))))))
```

Then anything prefixed by an underscore gets flattened:

```
(program
  (vector
    (boolean (true))))
```

Chris makes good use of this to make the grammar more readable. 👍

**Comment by pedrorgirardi** [comment]
It makes a lot of sense, thank you @shaunlebron !
