### ISSUE TITLE
metadata handling of symbols as compared with collections

### ISSUE THREAD

**Issue by sogaiu** [oakmac/tree-sitter-clojure#26]
It seems nice that for collections, (any expressed) metadata:
```
^{:a 1 :b 2} ["a" "b"]
```
is available as [something preceding the collection](https://github.com/oakmac/tree-sitter-clojure/blob/master/corpus/metadata.txt):
```
  (metadata
    (hash_map (keyword) (number (number_long))
              (keyword) (number (number_long))))
  (vector (string) (string))
```
The [corresponding portion of grammar.js](https://github.com/oakmac/tree-sitter-clojure/blob/master/grammar.js#L57_L62) is:
```
    _collection_literals: $ => seq(optional($.metadata), choice(
      $.list,
      $.vector,
      $.hash_map,
      $.set
    )),
```

This is different from the way it is currently done in rewrite-clj and IMHO is nicer to work with.  In rewrite-clj, one ends up having to traverse the metadata node structure to access the symbol which can be more involved than seems necessary.

In the version of grammar.js currently on master, this doesn't seem to be the case for [symbols](https://github.com/oakmac/tree-sitter-clojure/blob/master/grammar.js#L171_L176
) though:
```
    symbol: $ => $._symbol,
    _symbol: $ => choice(
      $.threading_macro,
      $._symbol_chars,
      $.qualified_symbol
    ),
```

Does doing something similar for symbols make sense?

FWIW, this came up in the process of trying to merge [the metadata portion of the corpus from Tavistock's repository](https://github.com/Tavistock/tree-sitter-clojure/blob/master/corpus/reader_macro.txt#L19_L53).

**Comment by oakmac** [comment]
Yes - I think metadata is important to "get right" here :+1: I am very open to PRs to help / fix.

Related thought: when considering which test cases to add to the corpus, I think we could borrow from @tonsky excellent [sublime-clojure](https://github.com/tonsky/sublime-clojure) project. I believe his test files are very thorough. I made a note to do this with [Issue #22](https://github.com/oakmac/tree-sitter-clojure/issues/22), but never followed up on that thought.

**Comment by sogaiu** [comment]
Thanks for the response -- will investigate further.

I didn't know about @tonsky's test cases, thanks for pointing that out.  Since there is no official specification for Clojure (though there is source), good examples seem even more valuable than otherwise.

BTW, I also found someone had forked Tavistok's repository and has made additional commits: https://github.com/SergeevPavel/tree-sitter-clojure

I haven't examined that very closely yet though.

**Comment by tonsky** [comment]
The file for Clojure is here https://github.com/tonsky/sublime-clojure/blob/master/syntax_test_clojure.cljc. I was creating it based on https://clojure.org/reference/reader and checking some details in the REPL once in a while. Sometimes SPEC is wrong, some details are just missing, so it’s closer to reality rather that to the letter of the docs

**Comment by sogaiu** [comment]
To clarify my remark about "recognized as invalid" above, what I meant was that there are tests that indicate that something is invalid, e.g. `INCORRECT STRINGS` at: https://github.com/tonsky/sublime-clojure/blob/master/syntax_test_edn.edn#L49

In tree-sitter-clojure I only see tests for things that are supposed to be valid.

Sorry if that was unclear.

**Comment by sogaiu** [comment]
I think I found another place that metadata can appear other than before symbols, collection literals, and other metadata.

Appropriately arranged for tagged literals will be read by the reader to return things that support IMeta, so IIUC in some cases, the following type of thing will make sense:
```
^{:data 8} #my-tag "seed-for-something-that-will-support-imeta"
```

Some relevant source code is: https://github.com/clojure/clojure/blob/clojure-1.10.1/src/jvm/clojure/lang/LispReader.java#L944_L984

Some relevant docs include the last paragraph at: https://clojure.org/reference/metadata#_metadata_reader_macros

> Note that metadata reader macros are applied at read-time, not at evaluation-time, and can only be used with values that support metadata, like symbols, vars, collections, sequences, namespaces, refs, atoms, agents, etc. Some important exceptions that don’t support metadata are strings, numbers, booleans, Java objects, keywords (these are cached and can be shared within the runtime), and deftypes (unless they explicitly implement clojure.lang.IMeta).

Apart from tagged literals, I haven't had any luck conjuring up things that could work, but may be there are also other places metadata can appear?

Perhaps it is not worth trying to constrain where metadata can appear in a tree-sitter grammar?
